package 学习;

import com.sun.xml.internal.ws.api.model.wsdl.WSDLOutput;

import java.util.Arrays;

public class _451根据字符出现频率排序 {

    public static void main(String[] args) {
        String b = "tkcccaltt";
        String l = "qcbkrbolomdwttlhqbldbuscinrsjrvmhjltvplkilimtfpkllobenptthmxfpfdiqrqjfbowklsnqvgfqaitsavhgraicmnvfklodarkcdikfocgxkrotwdubpuadbmerhlsrxdslrnamkwokedviqksjhtpsvpplxioxwsivnjrfiknxvwjqxmroawtxpxuntldepqlhwmmaahdxosiecqjqdmorqdvfklhkhukcvoqmdeajoqmndglphvpchtbmnadpjhhxrixdbcepwpdbxhfkfcgqvqqsmdqelijlksqtrhqpfxpqakadvrsmcrkpwtvanpibscdnufkcurgegxvigvvovwhdmabvqnmqxsqacueiddsdqxksrtgvhxhnftgrmanhrjhokcejbqchxjrbffftpncgsllnqktxbqanmbufonowkfamdckoghagdaqjudgaxvtoritlmmoasejeclgxdwbnxlnnscokkdirrqamiujphfdclghwpindgkjqxpmndxxolanjngrkaageffgtsxnpraxuwcgijtanqarhrjwawwclratfldpcasuhvufmngunxjmjunwcqopwxvpvkdvuccjsemcrwqbpbboghskihqfpogitihffqpwnusupfkjlvlxvkrcscmeexlqxfpbfbrlhnxkwjdkbmuhpejoxctugbknratxmwbjsgsovdlwjggougcxjounvvvbjsujjxwgeidhollucsifehvtopphjlelglswflqeosdmhicdvbkcoqjehnvljrnljclgacajifaxrdanskfwuaoathnxossakxjjsgnxkrvhddnrrgqceanjmwquqmkebltpkuxulnhmxbsxcedmpafoarmtpqggggcikpxkfraglfghvvhwnxgwbbtllvnwihuuifmiooxfiwkjjblhvnjlfnutemxeqhmdvwgwpuubgunfhphorlfuvoqvremqonxfjdgepkalvihlhhufxbcbaeoadwfdccpculskajkrfsqmjtbdqhicqgoucsblmgttnifqaidufrrgmagqedaptfjaopabtitwvhmwqqjvwobkkjdmkijqkaogpnlwbaavmlreqrocqjarbmjxemewnannuvrauqrwkrdcikkftrxrcrpjiqhheeofgpcrvfgthusiatdupgfenbgshteeofcpokppdcidlcxhhgdbdrcqjmncjnlonsirrphmqeonntbvhislrcxhirurgildxmrmkgcpsoatgiamgmwspidqqbdigkeenttiigjpkgomojfcfibfwugdsltvidwkowiwkhtwimjafvpjdmkwvvapwqlrnereuoiebcqtucrpkfoqkjcuoekgmxdffmwbvkjmnprgwfujpadwahppxaehljuxaenttlnmovmpvxmospfnonearsesvffbweebuaegtvdwsiagerumedgnmkmiifwsgtflrkmrogwtgiajvhqlktxhiptpfoacjsxjrbxenbexgvfaejccpsoonkjqtskaxqllgemrbonivsgbtojbvdltsshdubugqwaboempkmrpcflfqhgqkmxmiimbwcgdemwlkqoohdrfehvfedqphfjlqlaqtwrxkrvjsrkokmequpdhpdhwmxrwxmecbfekmfolwwihrhkckgvnjgtwicipatpfqoiuisqsvijjfdebglewrfvnnnvuspjtcjdghvlebwmnorjhhppbjpmujjixmitcoqqwibatijsberrdgbwqxgaufvsxxquutamnnlontbrowsvmmskcuhklbckutmeisurdegvurvlfomlehcchqmbtvxawihmwtjwrxiowmoiusaokpiopcnvdanuvvgdgokdvmrqvklgfdgtwgeocujpseuxrlujqsfbjdslqfvpoifmisqdamrwcptasdxouikxeotixdddrlgaavjmblvkkcdqatplkbsnfdlokfoavsiaofksnbudcetftdgxkkvdgedfisoarxukltrdvvgckpejufrtmoscohkfdeckhqcinoobhjugcbnurpdvjuckfvjhdrlxofjkfqkumtoakepnldjhplmblnaswsqgoajhuxfsnudpcokethwrqmrjqjgxvpkphpmpiuoniueddpvbxmibspjrehtmqqacbepktxgfxtautjqmrbxrpudkxaalhutievnrlaeabiqdtcfwiqmjvlxsjufedvkaillssgbivnupemjptxppglglkdrnkrotwfmawlevnatamvpnuppnbgqnlefigrxpmfoibngnicfxvofscqvsvsuwcjrnvueglrrecfhsgtudvwdvvkaxeqtrqiusjmwqmkwdjdodxcnewxshvmjlnhmtwcorbxudfqvwggujlqltxpkxsiagabanthqkmhxjitvujiickwmxhpsfmumanexiowcdekwsulpnkplbmsqiapsrlrvsmbqmbjlgirsuihcbjumdjfiwrhemixetgauhtwukattbwihbwpmckgmckonnrnberjkdlomaukiafgoukicfvhlldgiupvtlomdhtbeweeccfjotlwpudwfkuvtclvdsgigukhmhicawgbpekkdafmuwnewwdwajxgejahdibmtmqvtriufajrnhxlsqbadhsoegnsbdvssulwxktmwejvdnirpbdkutiqxlbbppvtghpmgfnknfmhejjamqtwcaqmnrfbnucboeexoufwlcbqacdgcfikolrrfhpfkdkkdmshhwkpadcjiqeuajbxpovqioqmhlwpvvsusuwodigaumgchtanfbtbfejvtuxplbsnofiteknnlnxqoteekktentqbhpueoimdnjaoeaxswtbfgbflutnrxlwillmenagwejwpltmvehtdhgluttriecmcoqbrjlcwflcfikmawqvqqbwnalhimkjpjhcrjjwsakebmnxbtggvkdpplbxcwlegdwpvgqmenteloufaejqjmdeslxrgslxanaieqslccqkthaxhrscoxjonjnnukebvosviwgtvkahjhidvjiucsvnkekuddvcfxowprfmndtbefusjvugxgakxfoevaxsahdlkqgorocjorfvmunrllrtvtrwixrbwxjebmrrlkeivessgpdtgiikehmtfqtxghrbueovrhbuswtlpfwfcfowliobmenurwklkrosuhcpmobhwpppfuswuphkulqihnfankaqeqwafflvevvkrsuefeinhedtidaktqfhbknglljhkgaeusexpghjdxowdjvxnlmaswqdxxmmfcbhhjdpcoxibgkxsoejkkvbiewgjrtmashsbsaeodvrjxoatdtwmwaledxxjcwpcwkmutmodglelkshhaeirwgpmllopcnfkftxgeovihajoipoweowltweqoltcargrijsaxgbgvvqmqmdxicqaeqjsjgwdfjkxxmfkbusnirjdlbaethorsmqapnpdqgbmbupevbivbuemrpmdwfhfflqtwowxkguaoksnqmlviokxrvgfqnvgmvqlgmecdlrspvwxvwmxuqbtelqssnikiikiaupdcvjemgjasfrbgrcjrsbbdpgcaofseaarikveemmbpdumgbgsrabeelaovwrqjhqfmedtahhkvadilrduuaabfiwgwbwuijfxodnaphskmcqnnadqrhgrfwqrmvvmapbhafkvkfwtttcsnouvqxumnnhboeejsilmqebabirtlcqatmafsxqcmgjmnoecfukioauslinldimxwbwghhdddaalrsfbcdqjdhkdjoidmunhxnoboagobdcnrqqmjouqxlddcjmdvwtqniqoirhuxabegilubmoejdxswrhcpxgcrllfvsqnvougxlijkgwxjawhxxlcsfwekvrnuexbsfcffqnloluqbqaddrhjncdhrhshnwoagfnhxhmcsdiggwngsklijwnloqumbidrdpengimnbgssdhnqfhxgfauqaaqsatingcxwsuevbncuovjbektncirwipgbrwumshouslgckhalphhagshlpgsmfwgtfjhovvjnplrevnfrhnihdidcfdbdimroderdhuakqgvtsfxeoavefkpimwudabvtuakkjeutglcgqrafdxeibddntxvewgmkpmsftgtqalqwqjouhkxcsqptkpcokkmtfrrcurgixmxdjltrrcvmgdmqcnvqtnhggopkfogfsbqfujvtkgnefdiodbnljimsrtuendrnsxreitwmbordqinlvejqgkcjpqjsfkibpqdxopvshcqrpdriwmtmhldjhoucuteqidxagpsgelkwrtomjmckhuwtcexntmumgqtvhsfqxaxsxqlrujordulohkilshhlaqbpkjohrkxmalhnhvpigdkexbreqtxhpcxogtvnrqkfvcmrmpviwjldsaiivbtocgpbuasiisqfvijnqpibtxwmhhhosqdbcnxkdqvrfijujsojfgjlhutpphnapqxxpfbxuugqblwcjklelloghicmrgsuerxcarejgtvftkvouhaasxabweedwxvsxelqwoqicfthmvijlkvlbqinbpptfximlitsqgfdalwxmnfufjcoaaeslsnnpakjwwpapqlepmqncjwmdoprqxwakterdrlijfxkcvkrqihrpjjuerflrdmpgmwxsluctvuhslstsivdsgqlbbcgsoaoafjpuedheomjoftcwtadupkqcgxauqjpqmpqqwrhojbgxagolrcaemgmgafcgxpivdxlxbgbgnbpnojgklsltwopnacubvcsqjaiimdphkglhgvltaimrmjravawmrruqhupmhgxxromoqdwvietvopsphwxauwqweciccbsgjlabvbmjlgaqmarjwtjfeimsicdtwkavsejburqwkosjpmphtbcsuijllehhkdimurnnncrfemsbglmroplajuprgqvngducqsfgjlgncaipkwqwffdonnwnixnnkjsavwamhoaxlkemjldoctmvhlgxcppixhdvmxiopsxsxswqfdmcujemxxwwsjcofmxcufdvrhlpwjncwhmkmhvuwphdkwipsioxvgkagvugbftkcntvavnftnjnkexrilptpdfanmjophwjdhjmkdegohevifihgvdglmumhueqaiphblggssuhahilwplxuoccqjwvtfldnxvtkdcexitriluommhcdgeuwtvcjxpandcoioeobplegfkpicwhkobgwqhmbspwaguikdvdincxtmafutwwkmrixsvlmpvgwxeibefevujlgipqaoqbjrtkrxwwrmhiagsgequihspapjwkkdefrgalfruoitwtokotlxriwrgnwphjeccnkjqlsxvckckagfapxrolkqecmsivvljpsmldialtwddgkwhrwojcewkiistxggtddnbtaguameqobgfckglemnixtpghvlgsngbkbajknhtpltardcmsieoodrbmecdmwoujtgjbqlkkbgqxiaeestdgkjwpllsiafkhwqgmvaggkhxmrrcrjsjpafdhrpspcldftowmuopexxexwghrojgqmgcfounqfxhdjisawmmuoewaaflgpatbwvbasdruatnabxcjsexvjxgbgqgnwiqtwairgfpttxxmbjggjwgiijepiviblhuwujjprqxugrlqdxvqcqcmjrivxoqifwbbbhtmtwqxkksmpcrgnddkoorikkaseovvfbfnnwmvokmpeiijshrchcbtbioiqnrjorqmfirwlrqksslrsvddsmgeuclscvnwgomrglqbpqxvrrbnmdlfbubtupxhamjleirtvbrxuvkpreuoakxrtrkkixraveebjhgdebeqkkhqlsctxlahbvqgbctuwuiqetnjclalpvobxfvfimnwshfroidevmdhnuumihoqnabctettlhapoxxthrkhbdwxesmmvvxqlcgkbpfojtpbngpmuoqotdqxsousrvrlckxsaokgjqunacvlonurcllqggwwuamqbskjbbmsdnndgeaqepqhwtvralqhpusiqbaqdarkxecchmcuwncjhlatbgegjsrcahigwlkawmnseljpvvlogmsoqvqdcdsxpeuekcprxnfuuxoaqjdpsutjvsnndffgqqscqfaqlpbapsraphcluufertcetcciidtpxnmtjdsvokkodjhlkmoadkbrsrrvrnhuxqvcjximarqdtoepwfqftoierbjekhoirarglucvfgnoxfhoafrckhimxemwdxhmutrxacshgjxaqqbawgsqhejsebasvgmhilumxcwckrhrvgsocxkpcxdvaqwjhvtkggegichhjivaoprquptwlpnwujvkjsffnwpeuevotnavddiwsilfdmrupehguhsxfshpkwqwbaksnsvwojlfjwnqcbkvxcrbpscgcsiasjrmlejdpclwowcsuihokvmscgrcnpmlprwwgselgklprsqbvjgbopbdgfddcmnahwrgucvgktdbkdoofepisartlbcibttpcrkmpfwftmsercoqnrkqwimtssurtloxikqbpuvibgbwxvgambgekhkssocqwegacsevcnlonpqslnhvccukxvkjmoecnokthhxpkcqagapovtjqaomcecfqosksnjlqpdwapbmgnjgloolrntgvsoewcklwifkgtmexhmwwalmavvxxbtclirneahbgvtmwcuifmcqtbesokktsvnptodijoxclebeiucbjvsadqoqmfuamaioouuhooexvoiblcvaelohxdpodplwsswatdvicquitsaspchfofnewmjecxhfhmocdcemgsjewicqvppaglxrjdkjsoimqmipnbltsgsfnjudvonrfgeepgmhddwfqymwkbanfuwbjmalorjxkuexbxoeuwrwnusobbfcxspbjbvpbhltoxpignqbopbiqdkaebbbkkevorsbvrdnqpwapjkvqxotajeuqsdtdtnealrhtnsnblhoeceklfaongrshtnbnwcawhjsdvgdadtmuqwwwcidjtxjjuwagjthiwksmbaopxdaxtqtcuuibhhdnvotwhakaguggxjatanlxukpofooatkwuhnjwvsrdshilkphgvlvccecunevuvgtoblrwnpuehtwiheeigdoioworsqnvpnssmamnwasjhabixwwquhfkobrpwrvujfcqxmsmqvvkbojadphxwglxmlvoiogbbinkkqtcmxlqnooltwfnmhbqiwifjjadjfbffcwqrmvteohxnckjgenviilvqjdtamhertnfxgtkfhoedndtvmhvodngfgxapehunegchuuoicbdmgtmaxbrkwqxraetnxrijlkpankwgvrujfjmivjqsacashbmcmewgkbtkltdgcvgrsekegjtilessdpcotcolqsoofaeixpcmfwhmshkdogfreofsfrriuxkcljkvgnhkgfsastdmraigkwwnqcxgagmbnvfeobgugbejuxbsucujwovafnxdlihaloenpbxrtuforrkvxljkoqrjebccffbjfsprrnbrwvmxslhfcunsucdkoqpiwusltciwuhffadrfvlxdnnlawfclrihxwxtovwmpqncexxopmcdoaojeojxcxccwnmutdogbfjqxvjinnxkpmxipcwkbogpotumjormotrrmqbsicufmphhielsqqtwviplrmrgncglvkobhkhupshxhlbanllqvmvdjhunosxwrkkisvbwqghpeordcjmvoigsdndjcegtjhlvccklvbxiqpilwrpepsbixiwjagrbmdcavtkfanpjdnjkcluoitxwdougbkjkcvhcgpbjjjgdtatwvhlsrmaljbxhlwwtenbtcwwcougokifppftjtlerqivnimaoatkstikvjavrhniobvvdekdvjdxhxkhdjxiaiofvjemnsxmtjxshhambdrfgbckcejunbwhqpasjuhrnjtigrnanwegkftcblsgxhjqocejoetpvbjxpuahjdtekdfxlnqfjbhxjkahltevkacjlhdblipnoupjocmljabgwpegjxdmfwuejtvwgxwsixlqdlpgisflxsaepkgmftassxwvaqrtnuadjxppvbfhesergehnlixbvdgircqaqtxliwgginhjvqbpwtuxweqrthvntvdaxvgisrktlufdbknmobpjahsemeunlbdvkrosvxvnuigticcsxvpfwshaxjbpmhonkpxbbqfgtikcdawxiamrkdwhfxnvtggbpajvhfeervaqcklmcboomnwpnmqvtobjalnfxnjaggsvesxivamllfbrakdbcqreojrcaiusbdxjsxmnqoacqnwunrmpatvuiihukovrsuxtdcbrtjbrlunsvxfhohmhhcftpimhlkseakvnheqbdtobigvdmmqwkhngmnjcrmjuahkrumlkarjknwlbrlibkfoxewelxdslmspfrldedoxnefjdolmhhoievjvkdgojukebxiqpukokxvwpsfmkarkgpivxvffvpxrmfttcswhrtfkwgaqinpgvtdkroaabwbghufkggbkblgfxkeisihtirrfbwinlartcmfxditqlfhpefbnqwrrbakhaumweggbnmdijxvxhjaalhqfcsnqgrwotjmjlpioqnapadojnabivrirpkmqadgunmjasuilsgdspfwfvclhklkbjofcxhjivwrkhufjmaudivgcwovncmmwghreluxjcwxpdqaowsurrcncbmxtufqopvgptlqrnfqwgixuivsulftexgkxcwwlupwuamnxotwjidurkagmfviifsfscommmwrjloflvhipbsoxdmirbdfowajvvfuabbnacbjnsspqamwvfbjlnwrojjmxduvjjbuhfpivetsmocddowqscxfifeqhlliovvoqwnktutretuvapugwqwqulsehhbuhnojklghxsbuopjvwpsjphckcltjwfprmauhenaqjgomtkrcuijdoxmdsfowlwuhfiwpaelekibatdfucaimjxdunamlikbpkteknaamihtqpdfdabqsriiurgujebwqdkaptbxguvevflaaxrihxlsthfxoxsstinxokgxmhqtoxqpkvartrfkkignnjwnprumxkrrwhrbdlvjbdqtebbaicjntcoqepwfldqesgpfvtbpobpfmwodfpgpcthlkqfcjferkluadwdrqapatxtlkomursevcoxmkjuhvvgrfmegpowlxgrkooeuqamhlxntmvcpmohjmuegmfnxccivrjgoiwgrffhojcurwffaoqdlollmdtqpmgklikdbjgegrbdulsqnohqcnkcjlrifnnqdqnlcgmocsaxjuvcjjjnosbawbujchghnbaokewdtgrihhwrlboqmeaouvmeepjbrscmsdeuqndvpxnpmfpkhdhedpjhmhwmidkurufrcnfiirkklnclnavkcqekrovjkvspqgtbbirxtxncbsitojeaspdpdmpqoprvocngenodhaxjgdsrejdvkexumskqvrxwepuwtfmufeggrbogenlklijljphdwtusjfgciplcfutqckfkihkhncpcvmxxsgaageucattewxhikaanqwjmhcdsgxqnijlstnwgojmdbfawrlwhmsibsrlcmkefjffgxhevasghnpakgrgqteannoruafrgvbwvdkpjovjalmvdcechftprajmoswjcdvghohfqbdoocubtfdrnlhpnvtmrrplpujwljnidjslqtitaohdsfbgjslivoxpohoeddewcvejaopdtfxhwkqwvxjskaxvpfdknnfjegrzukrreldpqdmnqnfrhigmcvagsxxitlhbvqgvkatkkxgnemqnwweooiwkricknnadlhpphlqrkpffplrwfjrkvweeejhjtlevnqdhrfbsbkrfccbnfbwbngcwsrfmvobbvkdvbnxoxrdnvtwqwhkrhbjxkrudcwrwjwgjpmjndejnhedahtotcwqgfquoukdeslelcsxqpkovrnnokuapawhvdxofrkatqcvuuojnrupvepwandkwxqwdtnbqcqptsdssdaifkjwnwrfxjpewbngqpdoipbiuknspikdjsscfpekuwjmjmuwevrlliitoobnbljkabgtvbqwgtbefigpiwocsetbbxoeceagrowswdequkguuptxcctdvnkbnvvgidnnotjwgubqijbknhcblrxvfrwmsivdfpasgwqpxnoobrraxcecddtiarpirxhdqrscridwhwudpkgfuwielxwuanuialdpjjchojjsqwdocecctmxgjwjjuugjauahahkipaldapsqkgtwutaahaeitaevckxrncpglpacjprqhkbbpnmldnorphhlvvpximdilmbwcpbwjovueqtwpehcxkolinjqbdwwfqwhlpskqthvtvmjrxjnlrkfvjueaiaqclgguhdfejgwmuhulerrtltsdcjundahsujbfxnovxdppfvaemcphsickqhpqmwcovqdggpomhvpnqgvmhcghmrtrdaoskljmmtjxvstpxfgmesbdvjgdspxstrpbopffsrnieopiqcewchobviptucvmpmuxbrncxtwrlckvcfkbkqdwbhcpckghjbnkqcbcliedkgkiuvxpmlakpnoitoquppamgbcufjiuamjaimdoqjgfiltujgvrrhhlkphkhgbvorommxxanbeptasfstvpjbkblladpgpheakgrqbmutdjcfkbhvhgoupvsgwhwjtikxefppebgbrrljdkattphqqxpqhwmbukqomjolfjiqqrhfgoefranwuxkagxadkuvgksffwtntahwjspnnklawevdwqvdkwvdppagfgpuqhviexejjvwihxrbuhfwexhaaclpswvepxjvowvjjktekvlnqsahjnjfjutjeefgbqfmbobfgrbgwgdxcropsalcueqmmtakgiqxkhkeathemtjxtfxfhbngwktpkqmqfrsmmjpagqhhutvfsnmtpppscocmffsppssdfvbpqoihfwqqacthclbxgrprgbdrlmsgncosxpcthnakvcossmdtssqhvmfmkgbenrxbdsvntpgbihdeucfgpbxgrhbjmahmviumeiblrmtosrevdfqkvxcokjiiacfpubfsqhggqvwikwxevgcgtltojkjjonbnsedfkknwbjojbqodsevbkfjxwttlhiuwbhmtawuduafxowaatpxerntbidqptmorhecndfmuqlkusrveaacpbmluishnbhaamltdkwgdnjfgfifgqwmbssaqfiivktqbjkrufrioesnfotiqejxmtfknqglxgiqffllkoxegngutgcgadsswmhbkqdakeewuswildxicpwjwmopaoieaghnioaxaujeffrkauboelrnajodwelxkbvpxcmqppobkioarcgvkiiwhudckodsuusvplhlqfeeblmkveemwxcfeolegubnwiniqsjidnkxtfeqomgngapkworsbnmqxuparwtapqirqhuscpjhkkhwpossksftarwoliubonhcirpqkppkenthfdiwcctwbxeiohemwngcccsdgehwtkswrhkebwwkkfjisumkixfjxcxbogklwremlcawpnwvddlmxxljemepplntrtgrgbsxtlsslieattuwmhjlrueukcejjgwiltljqdbcggxedclfsuhxrgmbisfuefxrmxpruknvrrhpddjbciumslmurqhktrlcdmhpvpmlrwvttevcbqaevsfouhkvwbreokjcmcqmbxigdnxpkxmwkmgisnpuevrqosimrmqiqeakspqcedwkrapidkvwpxueteredfnhfmowccwtwujirpjixpmvvvjcvhgceegrrirkjvmirlcaurlowevqxxqruewgsstomqrvqipkfidsanfupawpvgsaxkcrwwegglwrhnbbcklogdqblekcwbwjxsirqjsjxjjffrjfircffntnshojmceluuspxtmqodbjdphxohbvpqoaesuenoewgxitnlcjvbpfcfenfjhpshkrbftlkpxcvtioqbnocskkitxbvcfuqqfkqplgtvmpqkmwrpefwxcwnsqbgirsxtbddavfiamnajmnikxaahpclkipatnthbgcijirqwouvtwbvfpvkdkgbcojsmqvssdiikfqvckuhnmmintgsdkdwtsroddkpfqfkckensanocwvqvtkjwpptufokxvjftfbacrtbhrqkqcegtijpvcuqgwixbwsfldfikcxjaudcxsqsxidepkauanpuqpfpgbpubtoenripqvlusoaiuhfjlcldvxkctxbcposmqrfbtumdepasokknpwmsaobilgbsvsshxduihwlrevtltsxrtackausxnnjglqgokxltftaulpjttxmnqrvtncvitmimaxvbsgmuutefrvksprijfhfnqxslsenwfxjpohojfpfemagapbnvdutirmraemkcbjbcacrlqgurphomswsarqvtxxcpbmwrfdgifxfsuardilqiajilqjuhlkohimbkrhgkxpsnsofdacgktbvoijbemnljsnthufcqwjiorhosggwlawcjaqsktwdvpougwecskohtblowtoccsapeiebrqhetgimiamghbfxnutlxglirxafgspniciqdpctfkfxrggimiwppausopvkidjvjkpommecnlqtwprkanujuqrhklxpswitspwvqkwhhmmuxvxgquwipxtxvlhverggmkmpvejlvejimphswelgqnjshoudwesgwckttxmhnmirmfbxaxtspjtainoihqnlsqhrmwxramigjbogxcxmmtrrpxoobnwvoldrphltolbgrrnwkpvmovunffceccfeemodlchlgcldfnwglwhkwedukovklxkictbpbildkixungsiahnomdpgwdmquoocihdvjbakiwujatqllbgrqqwlrmboemqqarvgtumabdtcawiosusbslcucqteumatiagawccfnqdhdmkdvrrpbnlhcitkvmxesnwmmcpjemmakxhroiempoqgslpavmejmpvddvfmnqowfpoiticwsnrppccgefhuopedmttgrmchudiaoklxltgmumjumxrtsekwplchjphegmucfnafkpptqsglerbqpqhsefihtkonncsubcakoknoseirtupcuqlrckxgxuvlhmchjqlfqdiudbxakxejswpckspmpwwmvsnlpisvbdovtbugrdxmbktfeupkrprcpgcbrklupsrrcvofxxqfrdnbqrhgwameenjpafjrkhqaafftwexdbkxagqhswjrroslxujbumlusuakceknwdpirfcqubjpdlshpfqvndvdxhxtrsqrovbjmxhiopbhruinjtxmmjwaxrsdaixumaiikswkhxiidjsgmnrxrevikcqhhgoegdfqrpilocpsbbarheuefntnqcbjouwufaigswuvfjvfdgloeiqfgtpgsqwavbojsfqufothljdsrgtfkbwcvicdwvxfmopnleorlrekavailkhhrhwcdsufgrdwdtjhrlkvsfifeefarkqtjrhvwsulqetwcqtxfllrudoihfsrdonckqsdiadnoggscfnoolbuxdpljrolsvxtmewfxuquwxvurbbddfngfmlxsikgubwoinujnvupswatifewwhpimajldkfldarlellcjnhorewpijbxocgrgnsqsoijntqlbvunssqjlribxvnxlotrcmfeawsiucnvafxusvxjannaxjlffdnqantrwaubwufrpjdgawngixvupurcmqfpqqtxcnolvltqqsqeeucwtjknwixfapkfsegegfhwinujbqqfwrntjjsuwdhgjwvtgdecjphcxltuukqbothmcivjwgwnpgwamlercnqabnoshkdiulhrgwecojxdcpmumngxlfxxisnseoxlirgtodpbwdhpcaahgqmgtihilebecxejdmmrawnvowrcqtrkdwtfcgwccrcrjvlltgatnawhgilksoaejfwfiwmnokxpbhexrvcsobufwsvbcsmvrhtffksjfpjjcxwhoctvrbujguqxwhogescnbiqhaapmmtklifdmqijthvesauwwboefurvgpukshuprjobqknbsxpqmhddnxvjowncglncclcotqnoqokuwqinmccneqwqpxmgqcrgurvwaurcmgfdxajsddsgcdqbaqgstwrojpuqjhlmvjhoobcaabtthpewspkfxvnuqgqmfilmkhqukbkglmvpmocnmvjqfbmnjxsbehbtlqpgdclnmepaxxroxtdtmbimvipihevjamgdjdlfejlwtctkjxaveepwtdsiuhwfkllmfltncdxsnxgqudiwgmcwdpkkgifaivpixutopseepwljxwshbqrkodovspsjdskivndpcwctqacftqhqfitclbhssmfrrllurwtrdqahatllhqpbsucxkififioiugmlkxstcwikiioutisqjmmbeaiatbmvemlorqboakibxpchihqijqshhbacvqbbpwjmmracesbporqfufqplqucolmncwdtpcwwfdpowqlkteigksmovvsbgogkkbddesctmmwcpkwkikcbpgcmjfdfbkmqwtidufueqfmpgkjiusownstrhjjwgphqflubjkgbrhcvdxveadtgdmwpocktvnwrpafnddorhqaewacnthdbbvfegohuhftmneeiqxfmlcwkqxaennmginwiphqtdnmrggjckwldmdesbtpapnpgpftureenkxchswusiqxocnbkpuhcixlbwlshvunnkjfhbmnitvlmnxhkmspsalswwrtktjranfnquidojfvgwqmehvahxjsvgoifbsrjsbblcshjvawmmcbfaocbwbexojhhjpnocpdxukbueowfqeopilvrulaepesjsamxeojvaqrfiqmrroscwfapsxwtqopkvvqfqgmejnhmimsrhaxwlefcgfwnbxxlbghaxhmfuhccmlwvssdcfjkdkohbcxbuwlspiqjadhuxnorulnpwosarwqcamwpmmurtdlkmnwlksttxrxddwrxvqvxbwepdermtqiqskkiulmmgfrgjtfppcdwvbrklfdcqqvljlnlmjilpvtshhfxguexmmnajhankstdkpoltlwkvlgfgjtiluprnhijqdklqwcamgerqjipgpqavcolfudnbsdmnihvcntrqirgedftdxltfjofflstxgmddoblcwuqoouahcnvdvnnfolbcsdticmmaowensotvxfpqnapxrqiosegfagvdweiuxakgpstweunqnwxgjdcatudnnlbjlthijgdcxwiaubagjxpbxgesmajljsosaaaeviimkmjepecdblfhkrovcjaxvtfnfvfpcfjswlxrvvjwfccjdlqiphqaqwoldjesaxvuntlipmwawnfhbwsmccjxlmrljlwexnotgttqejqqlsaiublitlklfdvgxfdgaxcpkvpdnfbpmkrmuvendamfguudvgdacgspqajoigpnsgbncanlrthugaulmgfroiomqeqdhotbmmibnlorfctbonontfkrcowncrlsctvusooawwpxahqlffscltlriajtpadkxpnfntkddcpwrafetwxcsjvbaxbowpamiasfucvrgfpgahmracxutvlaarmvqpjqfawdpfadhqphwtdefairlimxsalidiqveohixtbruuhxrmdvcqlaelpoocwjjdtdxsweteicpipbusdlnbacfufmcbuncwdtnetgtixhitwtufvhanxogfobamhhedafxmfhhxupnpgnlvxrsdxfiecgicnerqkamkwoajjtadvaaksamlkpctjdqnphrhbvmgemvwmsaxmeeuommggtmakpsmvgkpedpiqihovvwdtiftdofcebwnwlnxorghmloqclmkourxrvvqbguqlkbbvocwermrbvqgsfwawwblilerhllifwfexjxjngvelqflpfnjumopgbixogjdqfqwutpqcxiasuwnstxwrnjlmpddghghofuhtwhldfnvnskodiovvsbhsgntpnlgvrixgpjdahmdnsjmsmsqhchdhoerjixgfpnodqeoioosddmbhorobojqngkmtjcrixjetjinvkkkugslkxngrgbekhplhqvnvlwjwrgjncjelldekhgkijxbpabaluhmdiuodjvibwrwhbativkboxrvukckqwifdrjjdifejierhqaierdtdrbsimjrvniqvdxmxxxeuncoubdlwuiaphhofhxvukifrronfwspuqbtgmreogsibrrlrdtgdupegbuwfugphgtsnidllwplcvrqvhveduwfvtlfbsmdgsqkaoaaofcjkwovrmvheseqoalmipclbsgkrfrtxkacrkjsfreignbfjassbudhhwxeowvewolhhrrxrhjfrgfmwckgvqexspsharmddrsgtewumfexeubgfpkkumptanidhforncfqxtijpmwhaiejvgdnfhldkpaqccmmgbfgbfqocuwlojwphaexcsahiwcwlbfwmabwctftnmmndiqgdnnqjvxxkbofqsrfiejcrvqjiejlsnbqreojlphmprvnsfjtjqgrikxwsvmhsxjtjvaqirrurwowjieojrpcncmdehvqcobjcjkgiclbopsrfwsawcmhbohjojvgdmiroaftcdxjhmhmfvtqrjfpugowaedqfwgclrpqatnweopidniosglcwrlusqpaixmwkvcdatlwmnsonhbsrtnixqgkterfdnaucmowllttrqoumtmdgvmrosvxfasppifevurprkmubqfuxadeiwpneasvwvrxvbaojafqjjhjnnhuqxfsaowmrjmdptpttqdcpochfhtrvgcgfpkwhfrgvgerircubmnbphgwdfigitijardaskjeapbhqqfsrvorbcduechpavifhfpimnfurllvbifgrnplniajipgmtutskcxxuhnxktctbimgtjpqkiwnxlhgkxaalabtrasgjwhrrijeneogjdeiqhkdvhhxajhfuxtqhvrhbreoqevgsakcvlomudqxdkrgnnqulhrgilootjljnaiduwdjoueasofnmbsepfnmqvgkauioclxdwrrtfcksokfbamagrwpkxiumfffmqqokktrqxmdforbucnsmkdpbgdqtttrvqinbknscncfkujxvdfrvcetavhdhspuiccfomwupxvlxgkrejmerjanoldmikahvwxntbpirmfkonfoieblqxqvvsauocxruuwnorqvpobmvrshtoewsltbuawkremkveaoreqtidshokidunhohgsdcoewrogcafnpkkpcgeawpaqsetxcpqncbmtiwjnkfamqtkhlqrkwskkurohlljdpikcjancruvvctgnvwbqbgrekmhnpbrejhqciqbvqneceseebiolptfjlffbicpjioncnuhnnjmaoxmswgodgqoxxesmwhekuvsdbnntkghkjeihmishqxuxxcmohorogmhmduugxvlwdixmtwsaehwisnegfjdovmmhupuxcxbupdibmbontjnkipsfawfjjlrjcamgfkjvkgmnghvxtljpcowswxoalcvexwwsaicrwhlbsrrwogsnpuhobtflssbikqqujiohkxfewqijmsiexihqibdbprfeuqllsrlqogjhestaexlftsmbmtacarrbmnxicfsdtvbrmjkuoosxsjpjeamqxqvpcxukcdlbisdleeevsngeuhqhqigqdqivogrkblorvhauosdcjgprrdomjlqffaelbkahhfsetciwrffeshnqsvdhvbquuhxksthkurjbbnswgmldfspjwfnjwkxqipcksrpdrxjkphiouhfgsoxegmvbupfhchvsqfarfptuwxqwdgcvcllabalqgwkrbxplmfbnjsornpdotjmjnqefpspnuqvivxsngcmglgurmgrefarsrhkeakqjwwxbgxegxfhvomlldmklidchipmnvjpevgigfiwrgmtbhvvalbfrfsxjjqehvfuvacapjaqedjqdihiqlvdhtnixnsitaaxnpipukqripsnkqmfcuiemcvmcsnjaxaidlcferqlujreihkdwfkqakankkkpprxxidpbhnbmbbfdcnlugoepvmqronxchoetepgeghrvgpfdktggxhmbqplrwknbjxxfwxbwrfkgeeleabtcmjdvudtndjnffcxvwmxhprshkigglvcqstsmpbomfcvhksgtfvawrcthbjoiursqefhwjqgqlopfimlxtlunwjmprbtetmfbqquddikpgmjxrkwahnlchfnxbxfahxlmgdxtvbcswunxcthpclfwdonpkdvviissxocfoefrkxslwqwelvtblnghtgrdxcdqdsukhifdclhetxmpdutspahpvpsrukorbvnkhojspdgcrkpqkpwtocighpqrgsluckvnpnberuovrrqgxoncrqsfkmmjwjdanoldpnwkpipvtcatkkwqpmtmnqusmhugddrdgggmcgrrwivfuclnrnelbdcmhvaouaphebcsjpullarvvgcjwtncwdnhpkvipolvtfstnbqbbtskvhndhphidcusvovmutowqshropvmbskwkudvdaiwbxjwjsprmjqrvbpcdgelcvippvtvlwruhtdtsnsbxarakrmpuqlqnslwclxuxkdsgnsbrpqsehkbpseisulbclfddfoswdnagfgifaivuobwtfrevcfhahnollagjrwooepahjkrgnivwbcvetpcxxdxsvvkxvqdoivawjwidvnobogbqotkbkpfxmnujokaxeabtruidvsluvhbjliplibrlhqvheefbnqdoieknfosovuvwtnqqbjmfxpnaaoclvnogwooknafiwvmxfmgwwqlokilmiioglhsmtcujwckbisqfrmbvwmjgcmbexktrphopajmlpdkcedpihnjobgnehefasexvsdtamrvpbdmljispipwripgrhoihtgtstvrghuqgdsstirjldkpvcvvemuckbihpstakkanxfaschhmtjwndassfoutqekcnqpqmmpmdxfnrbqkajlakauvgtqksvfolepalfpfksjtqdnfklbadevnfnpjqtxrsovbhwkxdnvmoxxtqxrfnduuklawbgcubpimkgxlxjxhemuncgbwboqqogfsfxmxjvawjvwjnmaocswdrhkfxmtcjvnvovhkjtvchugrwajhhbumfsviwnmbsqqgbarecwhpsjbdrnqdtcfknaiqpklhrawpbbegmawmsxgppbxchnltcinnbratilhouhxigqscalveqoullqfieskwffleutduskckrpdjehodlejqgvdrcxjfsdulqalbulvumtrjfcceqrnxrdfnugbirfuacjfubaaoqwvktmxpjhijdtdwdpcarsbkkgcpdedxuqvtqggltncwvevkpkunlkmtjpdqheoabxcfjhicbmloowlkpaxgpwgbpnoaikrjwfnqrpdkrdtipbvwuatfenvntpnhlfesukemwhbulscfqwtgndiqlxthgvwftnqttmjrqwiiaragqeojlagqlfghxitbwltdknlgqusvarfqideroxvnngauhxdvuwwlkfsfgknncjbwpupmnqvpqsxivsnxwgklksfmjplwwrehwgnlquxnnsfrcrdiemvdlogmsttbgshkeragqkjqenbawfexnpjlfqumqpvgatqasgoenkmjeldfivioshvlxjpwmsbnufjrqebhgfrfwulhrcpdcnakbqpqwehvloivndinechpjjbaqdbiwiurunmlfvxiuqhecmlppbvoorvwgagtfiaqaqohroruqcnvgobnwtvrmfxssbhuqnmhecomdwfspnjjsregbpgjutxmvpsvhqqnbskstolsiavinfdmbfioffwmorqnjimegiliaemtedicidonwvsiqtsrwxslpgakmfsplkggsxkhscoshqghnmuufkwiajuqtifptakmdsdpmtbdfvtctiffcbgmfbiwsroijejtpxdbwuaipnrlthdugmqxnondsbdkvarevtkwxxlagprqukqjiegirbjbkpoeweewvqaoqelvstbrpplejqpqqrnosdwqvwblingbirwnkbcadbluaasaugcleotebiijockoiqgbosmubvcswfrwsbpaopmbljaroavppjjjhfimjvxwlvlsebtvqotgskdtbwisokjmnsersakaodiokgibdtpvhkahpmbqfvvepsslvhdaieqatrfnhpaebbhuhtsrdkehomicrbsfqkljirbbtjpnjpqtbkcmihawsqqvxwxipmksjwwvhscghflngralwgibsxrwogsbeltanaljvishsciiojwmsgmpwisthkdaivpgmaqnlgxkdxauardipaukhlvnkblvdmgsxvnajbkvrsjtnjhhdkqafajewuixuargoistilrknwudebsigpqchawxtbtitpwaqixwxtwpoisfgkmnbmeiocuakknwjdhjgffrxrhmfcrrktneetfcjxdftpmkgekqppkuqwglrldpbfnwodjhbwdpnosdbajhexhobrjlmlxpdxmdiubbohvobjgllrluvunqlcsldcuqxjctbxwgpkhshhxamoiibwscnrqeajuegtqoclwpmqkkwrpttqpdiwiuaxdotqwjhgmdsqtugipigwfuqokvedngutdbdvsitrxlkpmmnseciwbtuiagcvliaoqebkiqbucospirihlruslapgrfffbjmxkrngqlkitmbibjaosebalsajvttkwkbobwwcchomefpdgvfhtnqtrlaqniueuthlfeeegfuiuioghfoducianbwepmrdkufpocixevfftgdeuitjpfkjxulmehciimubnssampacqhjkfavjdegnawpauqwsgvdjacbrglwhvdwcslemqptuworaajncmfdaaewbtigmbcstlspigijxstbvoqjptvenworijpbkelgvifxiforfvwjgqgxbbffjibbxkawiwicbjutjvadofpglmssqpepsqmgfmtohpxnwhwuvghwtugdvmgavfebknjjcrarnarpnqnblqllljswcxibpmdtiwgkpagwvhfseoheledcglfxffjogschvvealqgwuvvuvxfcwajcvmfxlfrpljjdqjteolaiekpnqnhntvltxdtvobadfpahrclfqamvupmgdgunsmkouihlfigleoomaatushsemceoaeorudotulawbsswjfecodvadqcovvphwwtsqmhjimaqjxfflesiktpsmdldwpnoweeqogvbxlnbnihxccqgficceqgshxnvpvjrhipssiirndaforggodohdxdtihreblbisewvitrhcrapaqmfnsksrbchsoplnfotxrssjmpltkwepxbgkwqsxekwvuxablwtphtineuwqxtfexoxwagaurvqprlohwchaobhvrgikgibgodaawflabrlkvcdhecivoljinoiabsbfnqsaknuekpcfitpiowntpcdoguhkomubmfvpkvlhopdbkxecevpmbhqiwiurxvttejimqhprdqgmdwxvhjvxehvvtbautuwstvepljidtmfqdilknqamifnvxbslssmosbiqsuqevjnnduniiliewqgqbodxdxvqsnnqxqmejqbrbuaposewmxipjjlgatsxcrtprnxlojwpookibunkutuchkjlqotdbnbdacpcwmpmltdsitkreukhdaftdxhvripguburqisrhtmfkfekosjannbqrpxublgpnapoupxpbnnrjlknamkuvpkrdwtirggoeqqldhxwtlfhefvleumdthtwhesrbjgmxrwxtjceutfhdcnlbqqohnkqgjuarlpihcjsnnhtlouxwubfxjoubbhgimkujwalmntfjchcsmtbfbksopnwsklbgguojiclhqbxqsrcancmispbgjfsqjgxwxjubcnsgewqqdgcfaaqpxrshbicnpxcshsbjuiitrajlowsbovwtqxvjndghrxkiwwsjnltnwhbplacexsvcesdegbuqcfncewbcxanlvuqojmlpdxwfnrdquhwojcvxakfsqmnpuhpoctuactxvrvffxiedvfbpljodrcuiepfruvwiehkqrosuokuwxhksvunlsabgvnsoibpaathandjtlfihxaxxgsbmtoubxahfgarwxwueefddekhwfhiivdsudvorsrdwwsuejqttilgfsbklbfnmebjntvfgniwbhfgaocdhpomqejqgcjhmjkugenmaruaocubewmnhkvedutjxbunovgoxtvaxgfsfinnoifatrjpqapngonataouqdxllmmlghbiavwedmkmokdftbnxtkcijlauusberhhujngbhkhdmqkqostcxkjrkslllslthciarawipebvmksgiijjnbliljgjwslkowdfagoilkhbncuaxnunwpctmarvpdqbpubsggfslmspxoxfmpovtutnvpnhmvdwlmjxtsdnpkbxkatnqppbdajdhokqpiedbwuuparbaevcpgsjsmwsfscpauhpptkqqckskjhwubvpebsirimgleoibsvethgdcxsquvunvccxkadchbjqeuogtrlqfehwwhvgodjfjxmirfwalqevadskeokjukwqlaknougosakmkocjvnfxgrblomjsajsstdkewjjjoevdlujvuavfqfmbicrqjbudvxeduqnfpfudohimcjeifrcubhcnhjltbgbdsbisujawjxjxohjxwdevdutakkicxwjlgwtinjamomefbmfcrmjmvjnksudjxqdlcvnibfvtmnrxjopbxukxxohrxxlpkexevaxrsvxfclxuhfavispqrkkpkljnwsxnxnaehqfbsgwedlqnvqhgdxnejpmjesiopfbaqhiatohpwpgjeutsndjofmnnmlvippjvochrntcogqkkwhccxxohhsdbpourwfjlxbduimoqmpwxurnijltxgrpmtlfmefblmmlbmsunjehansleegiujrinkcbociamvtajbvdguhaoarffwcpqcjipttibogxwtnbtifmsexwapqltqvflqdmxvfbejxvkmlhqhcgrdoeobneodqftkfwpkjfhtkdxkfcgptseacqjobipflfkkiwhrqdtnrinllbxbsqbsechvmqfqwnxhltnkpmxfsvvrundlnpdtmtlqnuitiwdjqwlfjhdngkwdkfihvppsbdswotivcafinhacvnatfoiqlsqdskhpvbwavoginsfmlvfbsnnbokekqltjtnssggwudvcloelfkaisrjkvlnbqjrxhsdjevkcdipcoaqimkrdvcwibkaxcoewpnsstkdlvteqbktdpdqwcfwoemcgiwdhqncximmilonlmlampmeicrjmwbmxkspdsceilnlctxsmhevuvgwbtaokxjvrqsprftitnlrhgxsjcvckhjgbwiobhlwnkgebjcnkupnjfwguooiohndbmcbagrxrrgfdgnmncrpixewfbhhblkfilgoaejpqtslqmvusfbrstiitepocvxnwfdnqjexhrjnhlcwtxwjjdmhoihgjegtmrtqafroauuubeubahkhmggbwdioxifgroeeibkvkkdqefcoxnduuuxpuhxxtivxnoplbtvdnnoaspfvsakqangqpcxifgffiiunkvlrjuuvddgvacpsaifvhwxcfbxblmtkdnmxxwxonxloscjsmisfucgferbsfkdrvniuhvfmcfesxissfchjxvfqrpmjhsgkxtpqxqposmtwxeipkxsaajumnjqoqmcobbqnrhnnldwvkhuuuxmtfftqwqniaaqneouqmcxjxewvrhgxbkmkqrjfxetahhigosmujrujfwtwlvgqmjumavicvorvgxjkkuvxxenogjvbibtqskkbnroicuaaurfqfwcbgdkprnmgrugxfpxlagupvijargkrrhctgodfocxuveqmewtxqcsgwqrooernvhenanaxvqquedgixrgiwoxvootcsncdshrwlrbwhpvvpxlswghuqcvotagtfhudovbppavblpxqncgtsxplbxsgaqrbierolsmxfmnrcavewdokddxwgthisnnoctpejgrxmtbwkdrkdbuqhknviaejdpcxluhmpskouxjhgorstgafqmrxiurucwihtxbpnefnwgeftdwtorkanrfvobvpisomldnmtwtersuptaaouskcxjpoiorsednosssmcwesfkpwuhhsobxcvujdidgxwjogbmrxrghptoorbwcatgkbpsjdvxbtouxexxleingfcfbjpxlpmrtofdphiefbveihuuouhkxjcragqjiqalskqpvhabjoksthilswhxlglbcxumckpcpuhhkkfwmnvuggmurdplkcgnqnbqrgbpjfkbfbxuxupldjparcigdvcwcpbenehlkvkhpdxbklxiadjnmmraiqqsiolsflquqtgxibegndvjfklfiikbhtgccbqccmmmmqgtxspliesauomwnxtbbfowqjwsuombnddbopojcffmuiukfbnqogaxjvhttchnffudtidomhgueaeagnhhoqclgodvphvxcwjixewdhjwknndpcusmjroexerbxohgwetqktnrieevhabrxveqojequwjfvpdmhkadmwkxsxifkapfwrpuwjsbmndcxruivwlrvvvumdksnwulgpdgbakgbaajgfpkcjjcmaesnqleskatrqgapqmorqxaccwcmsmgsfrawvstpltvnesqqootnuirsjaincdnxplwxtixfbobdchidekunnddhrgetawxluduibujtnaxtclxrkxrrljgstohgfoeoeqciagxlhbhfwinkxgcavcbjocpqrsfhqcibpwsmgscjdvkwuvpteeoftkfqdlaaqbwjpflflkgoelnvjxashrufsfcnlpxptwubacqpvsvnpriovjvvpittsdmakaavsakjjvdcfifwuhllqfxulkdnumvraovjfiiakhsnloibufmkukuxufmupjlimhuncupafxpsgmuwxueuwaffrlpauiimpfxhugnphfjxxaleettqridxtekjselxbxfaroewdbqvveemllrqsjuncxgockdhjgoqsckngmdebhwxocxsulkxfmeauesfhrkhwujulgeecctsdstanheevlkphrhjuirfwexsafsejekicdxavujobnsluskcqltrrqgindvwvvdielbsfsllkjsmcgdkslqeakvxuxfapnwrimlifkrmxpucsvkxdhigsjmucbtlxntmxfmimktbbqxmdhpcsilhqgdkjcnxemljbptudvrsqsclgfklamjxsqsijrmlxteinrskbatwtqppdwubvndnhpbvkpbrhixiuladhnjgthvijttwitxthdaslsspvvnlngfgnddshreoakrirvxhefhpmeioasmhbajnckrsqnuqbvmikdbcmmguwnewbfnniemwottgnefhemnoanplxrgjrtfohijvbhwssnswpehuinfswthuwcvfmasimdphmdhbgbmbvikmoclmkodlaberitnsnuwkcxidjnlaivhkwkgtuokbgguwmvnfmvqhdthpmlnlqnenhoaifrugixtjbvkjrguooafxpdusmpkmbfilujjcnodfwduotncpevtbbdoevlsqvhwednbvotdbeiddteskfcxgcnnlkscjlnkspwegsmcmdspkrcmwqqlwtiivedupcvuxlsswctsxcuijeiqvvovqufhdkghbtkurmetvohskstojumoffmhweljfnucbfrsbfjhlnbcvcjrccagpatagucitvdpfjegputwaxqchtnrdwmadfcijdttmjgfwpsblbrblfmcsuxhoxxvanbhhcucbccuegtrunlwfxfsmoqrbwrdapanijpgkpbuogipdakxhumsgjhbfdslreqkdpunxrsfgaamjrvsgfqcauufkflwedigreciihopcmdoljejvjstjhipqudkbnjbljbpfkustjsxuxactbqdldkogbcrpsslgojtnruwjiewtuqphfmleakrvursajlunkdkrvouerbkxhuxcegengbsnmouklunxogorwlcddsnrrusmomewtvawsubohwmtjsfndsjiwogjcjqffavpsjtiviaugqscmajuvdkrtnfxjlbegcwxjcdtgmbuxsaehhbadpdhshstpavlmagpisqoehmndferrxuxwngjsvfmlcuaeepiriksasjrkaijdaucvnbjeggloiwerniarfjhcuiwdtddmtqbbiovxlvahktprejhcxnnjnrvxxuqfaiekfuhucclxjdjuicheahlgvvnndnifnukxmdvtogenmxrejtgpinlivsifxvtvemujflxduhkcefqgxensnbtiejujdmrmeakpjmxewoxgxxwudvuvbbunkdlpqsclvimkxouaturqxldgehtruxwqqotpvxvsavcjabfutpjjtthesqcwubbbnumcldtaevuflvttxboqmgcvgjqddjmpbtaaromwcjbnqkgcorsobltrhlprjoicnfvqpbitqsssxqneqgtcseljgenhehwearntvswiiwhejasxvsdviisvjokwwglkcxgiecamcpacnqdlguihcxamshifgscpthjqtcmaemevtcbbcukharuhibgnvdsrubvccaduqenmeeebcctocoqnudlgkrkiuvexsgepfrrqhaesfgjtrosxfeipfelvetmhsdbkukbquebftiopeblutonjoufiltorkojempnvekcbuqabmhtfxqktwkaabfsfcblwnifpojipjwacxjrkacgoumevgjaeldihxvqvkjtpblncxfhsomdbqdabtpawneqqlwxhajlqnfbamedorghvtqvjhablwecqqtcxjlacdnkeuhwncadkeblqccebadiqxurkeobpvebpbeaaithxtqcuvpbtkjaqpjmdkdputawjtfjotfcmjdcvpfaxfwlxatdakikudlbjqrqaupwsfucmiojvpkjwcqfrewcuhtbisppvksbjhcejrrlpcfcuokdxifphwcqwjbuwwumiangtrnacoagkthncpvjtbhustgatgppahvbdaegrsjmhbrtjaxpqhcgusotdursjubmqhfnrojvubwundbciqlwnvrephmekpljlmipvkrbjkqknbfcavstffhfgixgdrkwecflthhifugtkjbhcmxxlqaebgkrvbpecouqdtfbqpiqttpqgakqajucijetqqitfkvpwbkwemvbbqopuglxdfthkshutugdoviaugofokpouxgkcakmfookxxkgxirmfhgteeixrsfgdagstfpogtdfqdvxerknbbnh";
        System.out.println(frequencySort(l));
        String s = b.replaceAll('c'+"", "");
        System.out.println(s.length());
        System.out.println(s);
        StringBuilder result = new StringBuilder();
        int count = 0;
        int current = 0;
        char currentChar = ' ';
        for (int k = 0; k < b.length(); k++) {
            for (int i = 0; i < b.length(); i++) {
                if (s.charAt(i)!=' '){
                    for (int j = i; j <b.length() ; j++) {
                        if (b.charAt(i) == b.charAt(j)){
                            current++;
                        }
                    }
                    count = count > current ? count : current;
                    currentChar = current >= count ? b.charAt(i) : currentChar;
                    current = 0;
                }

            }
            int index = 0;
            while (index<count){
                result.append(currentChar) ;
                index++;
            }
            b = b.replaceAll(currentChar + "", " ");
            count  = 0;
        }
        System.out.println(result);
//        System.out.println(b.replaceAll('c' + "", " "));
//        System.out.println(frequencySort(b));
//        for (char i = 'a'; i < 'z' ; i++) {
//            for (int j = 0; j < b.length() ; j++) {
//                if (b.charAt(j) == i){
//                    System.out.println(i);
//                }
//            }
//        }
    }
    public static String frequencySort(String s) {

//        "cccaaa"
        //一维整数数组存储个数从大到小
//        int[] result = new int[s.length()];
//        Arrays.fill(result,-1);
        //一维字符串数组存储大到小的字

//        String result = "";
//       String[] result1 = new String[s.length()];
//
//        Arrays.fill(result1,"");
//        //先统计有多少个字
//        int k = 1;
//        //索引为频率 数据为char
//        //存储上个存入数组的索引
//        int current = 0;
//        //右指针
//        int t = 0;
//        for (int i = 0; i <s.length() ; i++) {
//            t = i+1;
//
//            if (s.charAt(i)+"" == result1[current]){
//
//            }
//            else {
//                while (t < s.length()){
//                    if (s.charAt(i) == s.charAt(t)){
//                        k++;
//                    }
//                    t++;
//                }
//                for (int j = 0; j < k ; j++) {
//                    result1[k] += s.charAt(i);
//                }
//                current = k;
//                k = 1;
//            }
//
//
//        }
//        //遍历数组会把数组的值乘以索引存入result倒序
//        for (int i = result1.length - 1; i >0 ; i--) {
//            if (!(""==(result1[i] )) ){
//
//                result += result1[i];
//            }
//        }
//找到字符串的次数存入linkedlist 小写单次循环找到频率最高的字 再用空格替换该字

        //超时了
//        String result = "";
//
//        int count = 0;
//        int current = 0;
//        char currentChar = ' ';
//        for (int k = 0; k < s.length(); k++) {
//            //单次循环找到当前的频率最高的字符串
//            for (int i = 0; i < s.length(); i++) {
//                if (s.charAt(i)!=' '){
//                    for (int j = i; j <s.length() ; j++) {
//                        if (s.charAt(i) == s.charAt(j)){
//                            current++;
//                        }
//                    }
//                    count = count > current ? count : current;
//                    currentChar = current >= count ? s.charAt(i) : currentChar;
//                    current = 0;
//                }
//
//            }
//            int index = 0;
//            while (index<count){
//                result += currentChar;
//                index++;
//            }
//            //单次循环里把上次频率最高的字符串替换为" "  下次判断时直接跳过
//            s = s.replaceAll(currentChar + "", "");
//            count  = 0;
//        }


//所有的这个字符编号从0到127 存储128个 第0位存储该为字符编号 第1位存储频次
        StringBuilder result = new StringBuilder();
        int[][] array = new  int[128][2];
        char[] arrayChar = s.toCharArray();
        //这样子把所有的数组第0位变为了0到127
        for (int i = 0; i <128 ; i++) {
            array[i][0] = i;
        }
        //对应的频次加一
        for (int i = 0; i <arrayChar.length ; i++) {
            array[arrayChar[i]][1] ++;
        }



        //把二维数组一频次排序
        Arrays.sort(array,(i,j)->{
            if (i[1] != j[1]){
                return i[1] - j[1];
            }
            else return  i[0] - j[0];
        });

        for (int i = 127; i >=0 ; i--) {
            int index = 0;
            while (index < array[i][1]){
                result.append((char)array[i][0]);
                index++;
            }
        }
        return result.toString();

    }
}
